# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.103.0"


default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
   produce(app_name: 'Pre Flight Test')
   enable_automatic_code_signing(
    path: "platforms/ios/Pre Flight Test.xcodeproj"
   )
   gym(
    scheme: "Pre Flight Test",
    workspace: "platforms/ios/Pre Flight Test.xcworkspace",
    export_method: "app-store",
    clean: true,
    xcargs: "-allowProvisioningUpdates"
    )
   #build_app(scheme: "Pre Flight Test",workspace: "platforms/ios/Pre Flight Test.xcworkspace")
    upload_to_testflight
  end



  #lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    #cert
    #sigh
    #gym(scheme:"hello-world",workspace:"platforms/ios/hello-world.xcworkspace") # Build your app - more options available
    #testflight(team_id:"117835377")

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  #end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
