// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'eu-west-2:4f60b553-c548-41d3-b1f1-098aecd3c7df',
    'aws_cognito_region': 'eu-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'preflighttest-hosting-mobilehub-1776280724',
    'aws_content_delivery_bucket_region': 'eu-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2qhav0jtakmv0.cloudfront.net',
    'aws_mobile_analytics_app_id': '6d90bce88e1f426292e09bc21034400a',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '8ecc85ed-e771-4385-aa40-3019ecfe573f',
    'aws_project_name': 'PreFlightTest',
    'aws_project_region': 'eu-west-2',
    'aws_resource_name_prefix': 'preflighttest-mobilehub-1776280724',
}

export default awsmobile;
