// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_content_delivery_bucket": "relightest-20180831101527--hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://relightest-20180831101527--hostingbucket.s3-website-eu-west-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "eu-west-1:d641ba7c-0f12-4578-a228-cd5f06714b06",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_g7qplgNtI",
    "aws_user_pools_web_client_id": "4hql7tlv74h59oa7a9ro5ddrld",
    "aws_mobile_analytics_app_id": "644e454a695f4ebbb44171da94667220",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
